### ISSUE TITLE
uberwar does not work under compojure 1.1.2

### ISSUE THREAD

**Issue by ghost** [weavejester/compojure-example#5] opened 2012-09-03 08:56 UTC
Upgrade to version 1.1.2 of compojure,
was running "lein ring uberwar", there is no reaction
In 1.1.1 there was no problem.

The compilation, but to sleep in the [code](https://github.com/ring-clojure/ring/blob/1.1.4/ring-core/src/ring/middleware/multipart_params/temp_file.clj#L8) below.

https://github.com/ring-clojure/ring/blob/1.1.4/ring-core/src/ring/middleware/multipart_params/temp_file.clj#L8

Could you confirm? Thank you.

**Comment by weavejester** [comment] 2012-09-03 10:51
Confirmed. At least, there's something odd going on with Lein 1.7.1 and Lein-Ring. Lein 2.0.0-preview10 seems to have no issues. Lein 1.7.1 will work with ring/ring-core 1.1.2 but not 1.1.3 for some reason. Very little changed between those two versions, so I don't know why one would work and one wouldn't. I'll investigate further.

**Comment by weavejester** [comment] 2012-09-03 11:44
The cause is that `ring.middleware.multipart-params/wrap-multipart-params` creates a thread when it's called in Ring 1.1.2 and above. This causes the compilation to never return in Lein 1.7.1, because it's waiting for the thread to finish. I'll fix this in Ring and release a new version.

**Comment by ghost** [comment] 2012-09-03 13:02
Thank you for confirmation.
I wait for the next release.

**Comment by weavejester** [comment] 2012-09-03 13:50
Fixed in Compojure 1.1.3 (and Ring 1.1.5)

**Closed as completed** 2012-09-03 13:51 UTC
